### ISSUE TITLE
When connect to testnet, an error occured.

### ISSUE THREAD

**Issue by securekim** [leapdao/leap-node#119]
In, https://leapdao.readthedocs.io/en/latest/connect/

There is tip for
Connect to testnet: leap-node --config=https://testnet-1.leapdao.org

But when I execute the command, an error occured. Please check it.
Or How can I open the testnet in local?

leap-node --config=https://testnet-1.leapdao.org 
unhandledRejection Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/usr/local/share/.config/yarn/global/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/share/.config/yarn/global/node_modules/web3-providers-http/src/index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by sunify** [comment]
Outdated doc, i think. Try `http://node1.testnet.leapdao.org:8645`

**Comment by troggy** [comment]
@securekim due to major refactoring, we are setting up a new testnet and one of the nodes will be available at http://node1.testnet.leapdao.org:8645. Will update the doc once it running.

**Comment by securekim** [comment]
Thank you for your help.
