### ISSUE TITLE
Node fails on large deposits

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#128]
Could easily happen with token with a lot of decimals (e.g. 18)

```
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]: unhandledRejection Error: Assertion failed
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at assert (/usr/local/share/.config/yarn/global/node_modules/bn.js/lib/bn.js:6:21)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at BN._initNumber (/usr/local/share/.config/yarn/global/node_modules/bn.js/lib/bn.js:128:7)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at BN.init [as _init] (/usr/local/share/.config/yarn/global/node_modules/bn.js/lib/bn.js:78:19)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at new BN (/usr/local/share/.config/yarn/global/node_modules/bn.js/lib/bn.js:39:12)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at valueHex (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/output.js:19:64)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at Output.toRaw (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/output.js:93:21)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at /usr/local/share/.config/yarn/global/node_modules/leap-core/dist/util.js:145:59
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at Array.map (<anonymous>)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at arrayToRaw (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/util.js:145:32)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at Transaction.toRaw (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/transaction.js:470:90)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at Transaction.hex (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/transaction.js:343:56)
Jan 12 18:32:41 ip-172-31-26-236 leap-node[7081]:     at Object.NewDeposit (/usr/local/share/.config/yarn/global/node_modules/leap-node/src/eventsRelay.js:37:37)
```

**Comment by troggy** [comment]
similar cause with https://github.com/leapdao/bridge-ui/issues/95
