### ISSUE TITLE
Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#147]
```
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]: unhandledRejection Error: Returned values aren't valid, did it run Out of Gas?
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at ABICoder.decodeParameters (/usr/local/share/.config/yarn/global/node_modules/web3-eth-abi/src/in
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at ABICoder.decodeLog (/usr/local/share/.config/yarn/global/node_modules/web3-eth-abi/src/index.js:
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at Object.Contract._decodeEventABI (/usr/local/share/.config/yarn/global/node_modules/web3-eth-cont
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at /usr/local/share/.config/yarn/global/node_modules/web3-core-method/src/index.js:160:57
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at Array.map (<anonymous>)
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at Method.formatOutput (/usr/local/share/.config/yarn/global/node_modules/web3-core-method/src/inde
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at sendTxCallback (/usr/local/share/.config/yarn/global/node_modules/web3-core-method/src/index.js:
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at /usr/local/share/.config/yarn/global/node_modules/web3-core-requestmanager/src/index.js:147:9
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at XMLHttpRequest.request.onreadystatechange (/usr/local/share/.config/yarn/global/node_modules/web
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/share/.config/yarn/global/node_modules/xhr2-
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at XMLHttpRequest._setReadyState (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookies/di
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at XMLHttpRequest._onHttpResponseEnd (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookie
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at IncomingMessage.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/xhr2-cookies/dist
Jan 21 20:40:15 ip-172-31-26-236 leap-node[22978]:     at emitNone (events.js:111:20)
```

**Comment by johannbarbie** [comment]
seems related, and matches our version: https://ethereum.stackexchange.com/a/60309/2626
