### ISSUE TITLE
Reduce BATCH_Size for getPastEvents

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-node#243]
```
  ~  docker run -t -e 'DEBUG=*' -e 'CONFIG_URL=https://testnet-node.leapdao.org' -e 'RPC_PORT=1000' -p 1000:1000 quay.io/leapdao/leap-node 
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/opt/leap-node/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +1ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +0ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +1ms
  express:router:layer new '/' +0ms
  leap-node Syncing events... +0ms
unhandledRejection Error: Returned error: query returned more than 1000 results
    at Object.ErrorResponse (/opt/leap-node/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /opt/leap-node/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/opt/leap-node/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/opt/leap-node/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/opt/leap-node/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/opt/leap-node/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/opt/leap-node/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by pinkiebell** [comment]
like
```
diff --git a/src/utils/ContractsEventsSubscription.js b/src/utils/ContractsEventsSubscription.js
index aa64f35..6f772b9 100644
--- a/src/utils/ContractsEventsSubscription.js
+++ b/src/utils/ContractsEventsSubscription.js
@@ -7,7 +7,7 @@
 
 const getBlockAverageTime = require('../utils/getBlockAverageTime');
 
-const BATCH_SIZE = 5000;
+const BATCH_SIZE = 1000;
 async function getPastEvents(contract, fromBlock, toBlock) {
   const batchCount = Math.ceil((toBlock - fromBlock) / BATCH_SIZE);
   const events = [];
```
