### ISSUE TITLE
panic: Failed to process committed block

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#356]
## action:
1. checkout latest node at `5c84024769954b262eca48ff8660ae5efe3aad01`
2. yarn
3. `DEBUG=tendermint,leap-node* node index.js --config=https://testnet-node1.leapdao.org`

## expected:
sync to the top

## actual:
```
  leap-node:error not touched 0x197970e48082cd46f277abdb8afe492bccd78300 +0ms
  tendermint I[2019-11-05|15:39:17.839] Executed block                               module=state height=43897 validTxs=0 invalidTxs=1
  tendermint  +56ms
  tendermint I[2019-11-05|15:39:17.846] Updates to validators                        module=state updates=4881A447F30F484F046859530083FD27C5F7A70B:10,07ED56CB62B63E323FFDA95FD8FFE22E1CC13794:10
  tendermint  +7ms
  leap-node Height: 43898, epoch: 342, epochLength: 4 +65ms
  tendermint I[2019-11-05|15:39:17.848] Committed state                              module=state height=43897 txs=1 appHash=
  tendermint  +2ms
  tendermint panic: Failed to process committed block (43898:0FEC8F92FF48AB3A4503136238C6D3AD317AAAE79D5B29561D3EC70A1691DF8A): Wrong Block.Header.LastResultsHash.  Expected 697AC0DA637A4D63975EEEC4D0114CA918111C81B7B2C0DD7F9BE63F9EC40B40, got 6E340B9CFFB37A989CA544E6BB780A2C78901D3FB33738768511A30617AFA01D
  tendermint 
  tendermint goroutine 30 [running]:
  tendermint github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc00095e340)
  tendermint 	/Users/linkeex/go/src/github.com/tendermint/tendermint/blockchain/reactor.go:347 +0x1542
  tendermint created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
  tendermint 	/Users/linkeex/go/src/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x84
  tendermint  +16ms
Tendermint node crashed
```

**Comment by troggy** [comment]
duplicates https://github.com/leapdao/leap-node/issues/334
