### ISSUE TITLE
Can't sync events from local Rinkeby node

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/leap-node#394]
I get the following error once I change the rootnetwork  in the config.json to localhost:

`DEBUG=tendermint,leap-node* leap-node --config=config.json`

```
leap-node Syncing events... +0ms
unhandledRejection Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (/usr/lib/node_modules/leap-node/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (/usr/lib/node_modules/leap-node/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (/usr/lib/node_modules/leap-node/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (/usr/lib/node_modules/leap-node/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/usr/lib/node_modules/leap-node/node_modules/web3-core-method/src/index.js:473:33)
    at /usr/lib/node_modules/leap-node/node_modules/web3-core-requestmanager/src/index.js:147:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/leap-node/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/leap-node/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/leap-node/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/leap-node/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/leap-node/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

## Scope

- seems like I didn't reach the highest block from the rinkeby testnet:

`geth attach http://localhost:8454`

`eth.syncing`

```
  currentBlock: 5758489,
  highestBlock: 5758582,
  knownStates: 13800841,
  pulledStates: 13785744,
  startingBlock: 5758425
```

**Comment by troggy** [comment]
Please attach your config contents and CLI command you use to start the node. Please remove non-needed text from the bounty description

**Comment by troggy** [comment]
> seems like I didn't reach the highest block from the rinkeby testnet

if so, should I close the issue? 🤔

**Comment by MaxKuck** [comment]
> if so, should I close the issue? 🤔
Have to wait for full sync, try again once it's through. So far it never reached the highest block - waiting state entries to be synchronised . Couldn't get that info through the terminal.
