### ISSUE TITLE
"Output value is < 1" error when relaying some NFT deposits

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-node#397]
Depends on the value. Fails on testnet here (https://github.com/leapdao/leap-node/blob/v5.4.1/src/eventsRelay.js#L63). Possible workaround is using [bi](https://github.com/leapdao/jsbi-utils/blob/master/index.ts#L27) helper instead of plain BigInt, however need to figure out which values makes it fail in the first place and make these value illegal on a leap-core side

```
unhandledRejection Error: Output value is < 1
Dec 20 15:59:53 ip-172-31-31-90 leap-node[26799]:     at new Output (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/output.js:66:13)
Dec 20 15:59:53 ip-172-31-31-90 leap-node[26799]:     at Function.deposit (/usr/local/share/.config/yarn/global/node_modules/leap-core/dist/transaction.js:571:61)
Dec 20 15:59:53 ip-172-31-31-90 leap-node[26799]:     at Object.NewDeposit (/usr/local/share/.config/yarn/global/node_modules/leap-node/src/eventsRelay.js:63:23)
Dec 20 15:59:53 ip-172-31-31-90 leap-node[26799]:     at /usr/local/share/.config/yarn/global/node_modules/leap-node/src/utils/handleEvents.js:16:45
```

**Comment by troggy** [comment]
wrong theory
